blog/urls.py
from django.urls import path, include
from .views import (home, PostDetailView, 
                    PostCreateView, PostUpdateView, 
                    PostDeleteView, about, 
                    contact, categories,
                    category,CommentCreateView,tagView,
                    CategoryCreateView,CategoryUpdateView,CategoryDeleteView, CategoryListView, TagUpdateView, TagDeleteView, TagCreateView)

app_name = 'blog'

urlpatterns = [
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('categories/', categories, name='categories'),
    path('category/<int:pk>/', category, name='category'),
    path('category/tag/<int:pk>/', tagView, name='tag'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('post/new/', PostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>/update', PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post_delete'),
    path('post/<int:pk>/add_comment', CommentCreateView.as_view(), name="add_comment"),
    path('category/new/', CategoryCreateView.as_view(), name='category_create'),
    path('category/list/', CategoryListView.as_view(), name='category_list'),
    path('category/<int:pk>/update', CategoryUpdateView.as_view(), name='category_update'),
    path('category/<int:pk>/delete', CategoryDeleteView.as_view(), name='category_delete'),
    path('tag/create/', TagCreateView.as_view(), name='tag_create'),
    path('tag/<int:pk>/update', TagUpdateView.as_view(), name='tag_update'),
    path('tag/<int:pk>/delete', TagDeleteView.as_view(), name='tag_delete'),
]

superphysics/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('blog.urls', namespace='blog')),
    #reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="users/password_reset/password_reset.html"), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="users/password_reset/password_reset_done.html"), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="users/password_reset/password_reset_confirm.html"), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="users/password_reset/password_reset_complete.html"), name='password_reset_complete'),
]

handler404 = 'users.views.invalid_error'
handler500 = 'users.views.invalid_view'


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path, include
from .views import (register, profile, profile_update, login_view, logout_view, base)

app_name = 'users'

urlpatterns = [
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    path('profile-update/', profile_update, name='profile_update'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('base/', base, name='base'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from users.models import User
from django.urls import reverse
from multiselectfield import MultiSelectField
from PIL import Image
from .dict_lib import TAG_OPTIONS

# Data Category - i.e. Physics, Math, Chemistry
class ContentCat(models.Model):
    category_name = models.CharField(max_length=100, default=None)
    
    def __str__(self):
        return self.category_name

    def get_absolute_url(self):
        return reverse('blog:category_list')

# Content Tag - i.e. Nuclear, Optics, Environmental
class Tag(models.Model):
    tag_name = models.CharField(max_length=100, default=None)
    category = models.ManyToManyField(ContentCat, default=None, null=True)
    
    def __str__(self):
        return self.tag_name

# Curated Content - Free
class Post(models.Model):
    title = models.CharField(max_length=100, default=None)
    preview = models.CharField(max_length=5000, default=None)
    content = models.TextField(default=None, verbose_name="Content")
    date_posted = models.DateTimeField(default=timezone.now)
    read_time = models.IntegerField(default=5, verbose_name="Read Time", help_text="in minutes")
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag, default=None, null=True)
    featured_image = models.ImageField(default='default.png', upload_to='blog_pics', verbose_name="Featured Image")
    note = models.FileField(default=None, upload_to='notes', verbose_name="Notes", null=True, blank=True, help_text="(Optional)")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.pk})

# User Comment on Curated Content
class Comment(models.Model):
    user = models.CharField(max_length=100, default=None, verbose_name="Name")
    comment = models.TextField(default=None, verbose_name="Comment")
    date_posted = models.DateTimeField(default=timezone.now)
    post = models.ForeignKey(Post, default=None, on_delete=models.CASCADE, null=False, blank=False)

    def __str__(self):
        return self.user

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.post.pk})
    
# Data from RSS Feeds    
class RSS(models.Model):
    title = models.CharField(max_length=100, default=None)
    tag = models.ManyToManyField(Tag, default=None, null=True)
    summary = models.CharField(max_length=5000, default=None)
    content = models.TextField(default=None, verbose_name="Content")
    story_link = models.CharField(max_length=5000, default=None)
    media_link = models.CharField(max_length=5000, default=None)
    date_posted = models.DateTimeField(default=None)

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from .models import Comment, Post, Tag, ContentCat

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            'user', 'comment'
        ]
    

class PostForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ['title', 'preview', 'read_time', 'content' ,'tag', 'featured_image','note']

        widgets = {
            'tag': forms.SelectMultiple(choices=tuple(list(Tag.objects.all())))
        }

class TagForm(forms.ModelForm):
    
    class Meta:
        model = Tag
        fields = ['tag_name', 'category']

        widgets = {
            'category': forms.SelectMultiple(choices=tuple(list(ContentCat.objects.all())))
        }

blog/views.py
from typing import Any
from django.shortcuts import render, get_object_or_404, redirect, render
from users.models import User
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, FormView
from .models import Post, Comment
from .forms import CommentForm
from django import forms
from django.core.paginator import Paginator
from blog.models import ContentCat, Tag
from .forms import PostForm, TagForm


def home(request):
    return render(request, "blog/blog.html")

def about(request):
    return render(request, "blog/about.html")

def categories(request):
    # convert tuple to list of categories
    categories = ContentCat.objects.all()
    context = {
        'categories': categories
    }
    return render(request, "blog/cat.html", context)


def category(request, pk):
    posts = Post.objects.all()
    category = ContentCat.objects.filter(pk=pk).first()
    tags = Tag.objects.filter(category=category)
    posts = posts.filter(tag__in=tags)
    context = {
        'items': posts,
        'category': category.category_name,
        'tags': tags
    }
    return render(request, "blog/cats.html", context)

def tagView(request, pk):
    posts = Post.objects.all()
    tag = Tag.objects.filter(pk=pk).first()
    posts = posts.filter(tag=tag)
    context = {
        'items': posts,
        'tag': tag,
        'categories': tag.category.all()
    }
    return render(request, "blog/tags.html", context)

def contact(request):
    return render(request, "blog/contact.html")

class PostDetailView(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'], tag_objects = Comment.objects.filter(post=self.object), []
        for i in self.object.tag.all():
            try:
                tag_objects.append(Tag.objects.all().filter(pk=i.pk).first())
            except:
                pass
        context['tags'] = tag_objects
        return context

class PostCreateView(LoginRequiredMixin, FormView):
    template_name="blog/post_form.html"
    form_class=PostForm
    success_url="/users/profile/"

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.save()
        if self.request.POST:
            tags, tag_objs = self.request.POST['tag'], []
            for i in tags:
                try:
                    tag_objs.append(Tag.objects.all().filter(pk=i).first())
                except:
                    pass
            form.instance.tag.set(tag_objs)
            form.instance.save()
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post

    fields = ['title', 'preview', 'read_time', 'content', 'tag', 'featured_image','note']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

class CommentCreateView(CreateView):
    model = Comment
    fields = ['user', 'comment']

    def form_valid(self, form):
        form.instance.post = Post.objects.get(pk=self.kwargs["pk"])
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_id'] = self.kwargs["pk"]
        return context

class CommentDeleteView(DeleteView):
    model = Comment
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if post:
            return True
        return False
    
# Category Views
class CategoryListView(ListView):
    model = ContentCat

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tags'] = Tag.objects.all()
        return context

class CategoryCreateView(LoginRequiredMixin, CreateView):
    model = ContentCat
    fields = ['category_name']

    def form_valid(self, form):
        categories = ContentCat.objects.all()
        matched = categories.filter(category_name=form.instance.category_name)
        if len(matched) == 0:
            return super().form_valid(form)
        else:
            messages.info(self.request, "Category Already Exists, Rename Category")
            return redirect('blog:catgeory_create')

class CategoryUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = ContentCat

    fields = ['category_name']

    def form_valid(self, form):
        categories = ContentCat.objects.all()
        matched = categories.filter(category_name=form.instance.category_name)
        if len(matched) == 0:
            return super().form_valid(form)
        else:
            return messages.info(self.request, "Category Already Exists, Rename Category")

    def test_func(self):
        category = self.get_object()
        if category:
            return True
        return False

class CategoryDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = ContentCat
    success_url = '/users/profile/'

    def test_func(self):
        category = self.get_object()
        if category:
            return True
        return False


class TagCreateView(LoginRequiredMixin, FormView):
    template_name="blog/tag_form.html"
    form_class=TagForm
    success_url="/users/profile/"

    def form_valid(self, form):
        form.instance.save()
        if self.request.POST:
            categories, category_objs = self.request.POST['category'], []
            for category in categories:
                category_objs.append(ContentCat.objects.all().filter(pk=category).first())
            form.instance.category.set(category_objs)
            form.instance.save()
        return super().form_valid(form)

class TagUpdateView(LoginRequiredMixin, UserPassesTestMixin, FormView):
    template_name="blog/tag_form.html"
    form_class=TagForm
    success_url="/users/profile/"

    def form_valid(self, form):
        if self.request.POST:
            # get category keys
            form_request = dict(self.request.POST)
            print(form_request)
            categories = list(form_request['category'])
            category_objs = []
            # use category keys to get list of category objects
            print(categories)
            print(len(categories))
            for i in range(len(categories)):
                print(categories[i])
                category_objs.append(ContentCat.objects.get(pk=int(categories[i])))
            # get post object  
            tag_obj = Tag.objects.all().filter(tag_name=self.request.POST['tag_name']).first()
            tag_obj.category.clear()
            tag_obj.category.set(category_objs)
            print(category_objs)
            # save the tag with new info
            tag_obj.save()
        return super().form_valid(form)
    
    def test_func(self):
        return True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        categories = Tag.objects.all().filter(pk=self.kwargs['pk']).first().category.all()
        category_pks = []
        for category in categories:
            category_pks.append(category.pk)
        context['form'].fields['tag_name'].initial = str(Tag.objects.all().filter(pk=self.kwargs['pk']).first().tag_name)
        context['form'].fields['category'].initial = category_pks
        return context

class TagDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Tag
    success_url = '/users/profile/'

    def test_func(self):
        category = self.get_object()
        if category:
            return True
        return False

blog/templates/blog/about.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block header %}
<!--features-->
{% include 'blog/about_tags.html' %}
{% endblock header %}

{% block content %}
{% endblock %}

blog/templates/blog/blog.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block header %}
<header class="py-5">
    <div class="container px-lg-5">
        {% include 'users/messages.html' %}
        <div class="p-4 p-lg-5 bg-light rounded-3 text-center">
            <div class="m-4 m-lg-5">
                <h1 class="display-5 fw-bold">Welcome to PhysNotes</h1>
                <p class="fs-5">
                    We aim to provide a library of easy to understand material to many difficult topics in physics. 
                    Whether you are trying to do well in a college level physics course or just looking to expand your physics knowledge, you can browse and study our collection of material for free!
                </p>
                <a class="btn btn-danger btn-lg rounded-pill shadow px-3" href="{% url 'blog:categories' %}">Explore</a>
            </div>
        </div>
    </div>
</header>
<!--features-->
{% include 'blog/about_tags.html' %}
{% endblock header %}

{% block content %}
{% endblock content %}

blog/templates/blog/cat.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block header %}
{% endblock header %}

{% block content %}
<section class="py-5">
    <div class="container">
        <div class="col-lg-8 m-auto">
            <h1>Categories</h1>
            <hr />
            <ul class="list-group list-group-flush">
                {% for cat in categories %}
                    <li class="list-group-item">
                        <a href="{% url 'blog:category' cat.pk %}" class="text-dark">
                            {{ cat.category_name }}
                        </a>
                    </li>
                {% endfor %}
              </ul>
        </div>
    </div>
</section>
{% endblock %}

blog/templates/blog/category_confirm_delete.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block header %}
{% endblock header %}

{% block content %}
<section class="py-5">
    <article class="container">
        <div class="col-lg-8 m-auto">
            <h1>Delete</h1>
            <form method="POST" class="uniForm">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Are you sure you want to delete the following post:</legend>
                    <h2>{{ object.category_name }}</h2>
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-danger btn-marketing btn-block rounded-pill mt-4" type="submit">Yes, Delete</button>
                    <a class="btn btn-primary btn-marketing btn-block rounded-pill mt-4" href="{% url 'blog:category_list' %}">Cancel</a>
                </div>
            </form>
        </div> 
    </article> 
</section>
{% endblock %}

blog/templates/blog/category_form.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block header %}
{% endblock header %}

{% block content %}
<section class="py-5">
    <article class="container format-standard">
        <div class="col-lg-8 m-auto">
            <h3>Category</h3>
            <form method="POST" class="uniForm" enctype="multipart/form-data">
                        {% csrf_token %}
                        <fieldset class="form-group">
                            <div class="row">
                                <div class="col-lg-12">
                                    {{ form.category_name|as_crispy_field }}
                                </div>
                            </div>
                        </fieldset>
                        <div class="form-group">
                            <button class="btn btn-danger rounded-pill mt-4" type="submit">Submit</button>
                            <a class="btn btn-dark rounded-pill mt-4" href="{% url 'users:profile' %}">Back to Profile</a>
                        </div>
            </form>
        </div> 
    </div>
</section>
<!--markdown form editor-->
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
<script>
document.getElementById("id_content").required = false;
window.onload = function() {
    var simplemde = new SimpleMDE(
        {
            element: document.getElementById("id_content"),
            spellChecker: true,
        }
    )
};
</script>
{% endblock %}

blog/templates/blog/cats.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block header %}
<header class="py-5 bg-light border-bottom mb-4">
    <div class="container">
        <div class="text-center my-5">
            <h1 class="fw-bolder">{{ category }}</h1>
        </div>
    </div>
</header>
{% endblock header %}

{% block content %}
<section class="py-5">
    <div class="container">
        <div class="row">
            {% include 'blog/tag_btns.html' %}
            {% for item in items %}
            <div class="col-lg-3">
                <div class="card mb-4">
                    <a href="{% url 'blog:post_detail' item.id %}">
                        <img class="card-img-top" src="{{ item.featured_image.url }}" alt="Featured Image" />
                    </a>
                    <div class="card-body">
                        <h2 class="card-title">{{ item.title }}</h2>
                        <p class="card-text">{{ item.preview }}</p>
                        <a class="btn btn-danger rounded-pill shadow" href="{% url 'blog:post_detail' item.id %}">Learn more →</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

blog/templates/blog/comment_form.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block header %}
{% endblock header %}

{% block content %}
<section class="py-5">
    <article class="container">
        <div class="col-lg-8 m-auto">
            <h1>Add Comment</h1>
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="my-5">
                    <a class="btn btn-danger rounded-pill ml-3" href="{% url 'blog:post_detail' post_id %}">Cancel</a>
                    <button class="btn btn-success rounded-pill" type="submit">Comment</button>
                </div>
            </form>
        </div> 
    </article> 
</section>
<!--markdown form editor-->
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
<script>
document.getElementById("id_comment").required = false;
window.onload = function() {
    var simplemde = new SimpleMDE(
        {
            element: document.getElementById("id_comment"),
            spellChecker: true,
        }
    )
};
</script>
{% endblock %}

blog/templates/blog/contact.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block header %}
{% endblock header %}

{% block content %}
<section class="py-5">
    <div class="container">
        <div class="col-lg-6 m-auto">
            <h1>Contact Us</h1>
            <hr />
            <form name="cForm" id="cForm" method="post" action="https://formspree.io/f/xnqoovrj">
                <fieldset>
                    <div class="form-group">
                        <input name="cName" type="text" id="cName" class="mb-3 form-control" placeholder="Your Name" value="">
                    </div>
                    <div class="form-group">
                        <input name="cEmail" type="text" id="cEmail" class="mb-3 form-control" placeholder="Your Email" value="">
                    </div>
                    <div class="form-group">
                        <input name="cWebsite" type="text" id="cWebsite" class="mb-3 form-control" placeholder="Website"  value="">
                    </div>
                    <div class="message form-group">
                        <textarea name="cMessage" id="cMessage" class="mb-3 form-control" placeholder="Your Message" ></textarea>
                    </div>
                    <button type="submit" class="submit btn btn-dark rounded-pill">Submit</button>
                </fieldset>
            </form> 
        </div> 
    </div> 
</section>
{% endblock %}

blog/templates/blog/contentcat_confirm_delete.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block header %}
{% endblock header %}

{% block content %}
<section class="py-5">
    <article class="container">
        <div class="col-lg-8 m-auto">
            <h1>Delete</h1>
            <form method="POST" class="uniForm">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Are you sure you want to delete the following post:</legend>
                    <h2>{{ object.category_name }}</h2>
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-danger btn-marketing btn-block rounded-pill mt-4" type="submit">Yes, Delete</button>
                    <a class="btn btn-primary btn-marketing btn-block rounded-pill mt-4" href="{% url 'blog:category_list' %}">Cancel</a>
                </div>
            </form>
        </div> 
    </article> 
</section>
{% endblock %}

blog/templates/blog/social_links.html
<!--
<li>
    <a href="#0"><i class="fa fa-facebook" aria-hidden="true"></i></a>
</li>
<li>
    <a href="#0"><i class="fa fa-twitter" aria-hidden="true"></i></a>
</li>
<li>
    <a href="#0"><i class="fa fa-instagram" aria-hidden="true"></i></a>
</li>
<li>
    <a href="#0"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
</li>
-->

blog/templates/blog/tag_btns.html
<div class="d-flex mb-5">   
    {% for tag in tags %}
    <div class="badge bg-dark mx-3">
        <a href="{% url 'blog:tag' tag.pk %}" class="text-white">
            {{ tag.tag_name }}
        </a>
    </div>
    {% endfor %}
</div> 

blog/templates/blog/tag_confirm_delete.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block header %}
{% endblock header %}

{% block content %}
<section class="py-5">
    <article class="container">
        <div class="col-lg-8 m-auto">
            <h1>Delete</h1>
            <form method="POST" class="uniForm">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Are you sure you want to delete the following post:</legend>
                    <h2>{{ object.tag_name }}</h2>
                </fieldset>
                <div class="form-group">
                    <a class="btn btn-primary btn-marketing btn-block rounded-pill mt-4" href="{% url 'blog:category_list' %}">Cancel</a>
                    <button class="btn btn-danger btn-marketing btn-block rounded-pill mt-4" type="submit">Yes, Delete</button>
                </div>
            </form>
        </div> 
    </article> 
</section>
{% endblock %}

blog/templates/blog/tag_form.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block header %}
{% endblock header %}

{% block content %}
<section class="py-5">
    <article class="container format-standard">
        <div class="col-lg-8 m-auto">
            <h3>Tag</h3>
            <form method="POST" class="uniForm" enctype="multipart/form-data">
                        {% csrf_token %}
                        <fieldset class="form-group">
                            <div class="row">
                                <div class="col-lg-6">
                                    {{ form.tag_name|as_crispy_field }}
                                </div>
                                <div class="col-lg-6">
                                    {{ form.category|as_crispy_field }}
                                </div>
                            </div>
                        </fieldset>
                        <div class="form-group">
                            <a class="btn btn-dark rounded-pill mt-4" href="{% url 'blog:category_list' %}">Back</a>
                            <button class="btn btn-danger rounded-pill mt-4" type="submit">Submit</button>
                        </div>
            </form>
        </div> 
    </div>
</section>
<!--markdown form editor-->
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
<script>
document.getElementById("id_content").required = false;
window.onload = function() {
    var simplemde = new SimpleMDE(
        {
            element: document.getElementById("id_content"),
            spellChecker: true,
        }
    )
};
</script>
{% endblock %}

blog/templates/blog/tags.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block header %}
<header class="py-5 bg-light border-bottom mb-4">
    <div class="container">
        <div class="text-center my-5">
            <h1 class="fw-bolder">{{ tag.tag_name }}</h1>
        </div>
        <div class="d-flex">
            <p>Categories <i class="bi bi-arrow-right-short"></i>&nbsp;&nbsp;</p>
            {% for category in categories %}
                <a href="{% url 'blog:category' category.pk %}" class="mr-3">{{ category.category_name }}</a>
            {% endfor %}
        </div>
    </div>
</header>
{% endblock header %}

{% block content %}
<section class="py-5">
    <div class="container">
        <div class="row">
            {% for item in items %}
            <div class="col-lg-3">
                <div class="card mb-4">
                    <a href="{% url 'blog:post_detail' item.id %}">
                        <img class="card-img-top" src="{{ item.featured_image.url }}" alt="Featured Image" />
                    </a>
                    <div class="card-body">
                        <h2 class="card-title">{{ item.title }}</h2>
                        <p class="card-text">{{ item.preview }}</p>
                        <a class="btn btn-danger rounded-pill shadow" href="{% url 'blog:post_detail' item.id %}">Learn more →</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}