blog/urls.py
from django.urls import path, include
from .views import (home, PostDetailView, 
                    PostCreateView, PostUpdateView, 
                    PostDeleteView, about, 
                    contact, categories,
                    category,CommentCreateView,tagView,
                    CategoryCreateView,CategoryUpdateView,CategoryDeleteView, CategoryListView, TagUpdateView, TagDeleteView, TagCreateView)

app_name = 'blog'

urlpatterns = [
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('categories/', categories, name='categories'),
    path('category/<int:pk>/', category, name='category'),
    path('category/tag/<int:pk>/', tagView, name='tag'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('post/new/', PostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>/update', PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post_delete'),
    path('post/<int:pk>/add_comment', CommentCreateView.as_view(), name="add_comment"),
    path('category/new/', CategoryCreateView.as_view(), name='category_create'),
    path('category/list/', CategoryListView.as_view(), name='category_list'),
    path('category/<int:pk>/update', CategoryUpdateView.as_view(), name='category_update'),
    path('category/<int:pk>/delete', CategoryDeleteView.as_view(), name='category_delete'),
    path('tag/create/', TagCreateView.as_view(), name='tag_create'),
    path('tag/<int:pk>/update', TagUpdateView.as_view(), name='tag_update'),
    path('tag/<int:pk>/delete', TagDeleteView.as_view(), name='tag_delete'),
]

superphysics/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('blog.urls', namespace='blog')),
    #reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="users/password_reset/password_reset.html"), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="users/password_reset/password_reset_done.html"), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="users/password_reset/password_reset_confirm.html"), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="users/password_reset/password_reset_complete.html"), name='password_reset_complete'),
]

handler404 = 'users.views.invalid_error'
handler500 = 'users.views.invalid_view'


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path, include
from .views import (register, profile, profile_update, login_view, logout_view, base)

app_name = 'users'

urlpatterns = [
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    path('profile-update/', profile_update, name='profile_update'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('base/', base, name='base'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from PIL import Image
from django.urls import reverse

APPROVED_OPTIONS = (
    ("YES", "YES"),
    ("NO", "NO")
)

class Manager(BaseUserManager):
    def create_user(self, first_name, last_name, email, password=None):
        if not email:
            raise ValueError("Users must have an email address")
        if not first_name:
            raise ValueError("Users must have a first name")
        if not last_name:
            raise ValueError("Users must have a last name")

        user = self.model(
            first_name=first_name,
            last_name=last_name,
            email=self.normalize_email(email),
            password=password,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, first_name, last_name, email, password):
        user = self.create_user(
            first_name=first_name,
            last_name=last_name,
            email=self.normalize_email(email),
            password=password,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    email = models.EmailField(verbose_name="Email Address", max_length=60, unique=True)
    date_joined = models.DateTimeField(verbose_name="Date Joined", auto_now_add=True)
    last_login = models.DateTimeField(verbose_name="Last Login", auto_now_add=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    first_name = models.CharField(max_length=30, default="", null=False)
    last_name = models.CharField(max_length=30, default="", null=False)
    approved = models.CharField(choices=APPROVED_OPTIONS, default="NO", verbose_name="Approved", max_length=3)      

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    objects = Manager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin
    
    def has_module_perms(self, app_label):
        return True


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.png', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.email} Profile'

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate
from .models import Profile, User

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(max_length=60)
    
    class Meta:
        model = User
        fields = ['email', 'password1', 'password2']

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['email']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

class LoginForm(forms.ModelForm):
    password = forms.CharField(label="Password", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['email', 'password']

    def clean(self):
        email = self.cleaned_data['email']
        password = self.cleaned_data['password']
        if not authenticate(email=email, password=password):
            raise forms.ValidationError("Invalid Login")

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm, LoginForm
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import User

def invalid_error(request, code):
    messages.warning(request, f'Invalid Request {code}')
    return render(request, 'users/404.html')

def invalid_view(request):
    messages.warning(request, f'Invalid Request')
    return render(request, 'users/404.html')

def register(request):
    form = UserRegisterForm()
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('users:login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})

@login_required(login_url='users:login')
def profile(request):
    return render(request, 'users/profile.html')

@login_required(login_url='users:login')
def profile_update(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('users:profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
    
    context = {
        'u_form': u_form,
        'p_form': p_form,
    }
    return render(request, 'users/profile_update.html', context)

def logout_view(request):
    logout(request)
    return render(request, 'users/logout.html')

def login_view(request):
    context = {}

    user = request.user
    if user.is_authenticated:
        return redirect('users:profile')

    if request.POST:
        form = LoginForm(request.POST)
        if form.is_valid():
            email = request.POST['email']
            password = request.POST['password']
            user = authenticate(email=email, password=password)
            if user and user.approved == 'YES':
                login(request, user)
                return redirect('users:profile')
            elif user and user.approved == 'NO':
                messages.info(request, f'Thanks for registering, but you are not approved to access to this application. If you wish contribute, contact Digital Studio.')
                return redirect('blog:home')
    else:
        form = LoginForm()
    context['form'] = form

    return render(request, "users/login.html", context)

def base(request):
    return render(request, "users/base.html")

users/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>

    <!---basic page needs-->
    <meta charset="utf-8">
    <title>PhysNotes</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!--mobile specific metas-->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!--favicons-->
    <link rel="shortcut icon" href="{% static 'logo/logo.svg' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'logo/logo.svg' %}" type="image/x-icon">

    <!-- Bootstrap DataTables -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap5.min.css" rel="stylesheet" />
    <!-- Bootstrap icons--> 
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />

    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />

    <!--markdown form editor style-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
    <style>
        pre:first-child code {
            display: none;
        }
    </style>
    <!--google adsense link-->
    <script data-ad-client="ca-pub-9830295599870480" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- Google tag (gtag.js) -->
   <script async src="https://www.googletagmanager.com/gtag/js?id=G-W5VSVLLSMR"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-W5VSVLLSMR');
    </script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container px-lg-5">
            <a class="navbar-brand" href="{% url 'blog:home' %}">
                <img src="{% static 'logo/logo.svg' %}" width="30%" height="30%">
                <span class="font-weight-bold" style="font-weight: bolder;">PhysNotes</span>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item"><a class="nav-link" href="{% url 'blog:about' %}">About</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'blog:categories' %}">Categories</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'blog:contact' %}">Contact</a></li>
                    {% if request.user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'users:profile' %}"><i class="bi bi-gear-fill"></i> &nbsp;Settings</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'users:logout' %}">Logout</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% block header %}
    {% endblock header %}
    {% block content %}
    {% endblock content %}

    <!-- Footer-->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">
                Copyright &copy; PhysNotes 2020. Developed by 
                <a href="https://digitalstudio.dev/" class="text-white">Digital Studio</a>
            </p>
            <p class="m-0 text-center text-muted">
                {% if not request.user.is_authenticated %}
                Admin 
                <a href="{% url 'users:login' %}" class="text-muted">Login</a>
                {% endif %}
            </p>
        </div>
    </footer>

    <!-- Bootstrap core JS-->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
    <!--markdown scripts-->
    <script>
        (function() {
            var i, text, code, codes = document.getElementsByTagName('code');
            for (i = 0; i < codes.length;) {
                code = codes[i];
                if (code.parentNode.tagName !== 'PRE' && code.childElementCount === 0) {
                text = code.textContent;
                if (/^\$[^$]/.test(text) && /[^$]\$$/.test(text)) {
                    text = text.replace(/^\$/, '\\(').replace(/\$$/, '\\)');
                    code.textContent = text;
                }
                if (/^\\\((.|\s)+\\\)$/.test(text) || /^\\\[(.|\s)+\\\]$/.test(text) ||
                    /^\$(.|\s)+\$$/.test(text) ||
                    /^\\begin\{([^}]+)\}(.|\s)+\\end\{[^}]+\}$/.test(text)) {
                    code.outerHTML = code.innerHTML;  // remove <code></code>
                    continue;
                }
                }
                i++;
            }
            })();
    </script>
    <script async src="https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/1.1.0/marked.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $('.content-markdown').each(function(){
                var content = $(this).text()
                var markedContent = marked(content)
                console.log(markedContent)
                $(this).html(markedContent)
            })
        })
    </script>
</body>
</html>

users/templates/users/login.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block header %}
{% endblock header %}

{% block content %}
<section class="py-5">
    <div class="row">
        <div class="col-lg-6 m-auto">
            <h1>Login</h1>
            <p>
                If you don't already have an account please <a href="{% url 'users:register' %}">register</a>
            </p>
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="my-5">
                    <button class="btn btn-marketing btn-dark rounded-pill" type="submit">Login</button>
                    <a class="text-dark ml-3" href="{% url 'password_reset' %}">Forgot Password</a>
                </div>
            </form>
        </div> 
    </div> 
</section>
{% endblock %}

users/templates/users/logout.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block header %}
{% endblock header %}

{% block content %}
<section class="py-5">
    <div class="row">
        <div class="col-6 m-auto">
            <h1>Logout</h1>
            <p>You have been logged out. Go <a href="{% url 'blog:home' %}">Home</a></p>
        </div> 
    </div> 
</section>
{% endblock %}

users/templates/users/messages.html
{% if messages %}
    <div class="row">
        <div class="col-lg-10 m-auto">
        {% for message in messages %}
            <div class="alert alert-{{  message.tags }} my-5" style="border-radius: 2rem;">
                {{ message }}
            </div>
        {% endfor %}
        </div>
    </div>
{% endif %}

users/templates/users/profile.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block header %}
{% endblock header %}

{% block content %}
<section class="py-5">
    {% include "users/messages.html" %}
    <article class="container overflow-auto">
        <div class="col-lg-12 m-auto">
            <h1 class="text-center font-weight-bold">Settings</h1>
        </div> 
        <div class="col-lg-8 m-auto">
            <h3>Options</h3>
            <hr />
            <div class="d-flex mb-4">
                <div class="ml-3">
                    <a class="text-dark" href="{% url 'blog:post_create' %}"><h6 class="mb-1">New Post</h6></a>
                </div>
            </div>
            <div class="d-flex mb-4">
                <div class="ml-3">
                    <a class="text-dark" href="{% url 'blog:category_list' %}"><h6 class="mb-1">Categories</h6></a>
                </div>
            </div>
            <div class="d-flex mb-4">
                <div class="ml-3">
                    <a class="text-dark" href="{% url 'users:profile_update' %}"><h6 class="mb-1">User Information</h6></a>
                </div>
            </div>
        </div> 
    </article> 
</section>
{% endblock %}

users/templates/users/profile_update.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block header %}
{% endblock header %}

{% block content %}
<section class="py-5">
    <div class="row">
        <div class="col-lg-6 m-auto">
            <h1>Update</h1>
            <form method="POST" enctype="multipart/form-data">
                {%  csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Profile Info</legend>
                    {{ u_form|crispy }}
                    {{ p_form|crispy }}
                </fieldset>
                <div class="form-group border-top pt-3">
                    <button class="btn btn-danger btn-marketing btn-block rounded-pill mt-4" type="submit">Update</button>
                    <a class="btn btn-dark btn-marketing btn-block rounded-pill mt-4" href="{% url 'users:profile' %}">Back to Profile</a>
                </div>
            </form>
        </div> 
    </div> 
</section>
{% endblock %}

users/templates/users/register.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block header %}
{% endblock header %}

{% block content %}
<section class="py-5">
    <div class="row">
        <div class="col-lg-6 m-auto">
            <h1>Register</h1>
            <p>
                If you already have an account please <a href="{% url 'users:login' %}">login</a>
            </p>
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="my-5">
                    <button class="btn btn-marketing btn-dark rounded-pill" type="submit">Register</button>
                </div>
            </form>
        </div> 
    </div> 
</section>
{% endblock %}